name: Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch: 
  schedule:
    - cron: '30 02 * * *'
    - cron: '00 14 * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Steup Node and NPM
        uses: actions/setup-node@v6.5.0

      - name: setup Newman and html report
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run the Postman Collection With newman
        run: |
             newman run 'Inwarranty-flow-Collection ExtData.postman_collection.json' \
             -e QA.postman_environment.json \
             -d testdata.csv \
             -r cli,htmlextra \
             --reporter-htmlextra-export ./newman/index.html

      - name: Archive reports
        if: always()
        uses: actions/upload-artifact@v7.0.1
        with: 
          name: Newman Report
          path: newman/*.html

      - name: GitHub Pages action
        if: always()
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token : ${{ secrets.GITHUB_TOKEN}}
          publish_dir : newman/
          
          


    
  











      
